version: '3.8'
services:
  db:
    container_name: db
    image: postgres:13.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: challenge
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      TZ: Asia/Tokyo
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5431:5432'
  test-db:
    container_name: test-db
    image: postgres:13.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: challenge_test
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      TZ: Asia/Tokyo
    volumes:
      - test-db-data:/var/lib/postgresql/data
    ports:
      - '5430:5432'

volumes:
  db-data:
    driver: local
  test-db-data:
    driver: local
