name: test
on:
  push:
    paths:
      - 'backend/**'
defaults:
  run:
    working-directory: backend

jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: back/yarn.lock
      - run: yarn install --frozen-lockfile
      - run: yarn test
